/** API Spec 0.4.0 §4 — 문자열을 그대로 사용. 대소문자 보정·별칭 금지. */

export const DocumentSourceType = Object.freeze({
  TEXT: 'TEXT',
  FILE: 'FILE',
})

export const ReviewDecision = Object.freeze({
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
})

export const AnalysisKind = Object.freeze({
  DOCUMENT: 'DOCUMENT',
  ANSWER: 'ANSWER',
  REVISION: 'REVISION',
})

export const AnalysisStatus = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
})

export const RequirementStatus = Object.freeze({
  EXTRACTED: 'EXTRACTED',
  AMBIGUOUS: 'AMBIGUOUS',
  CLARIFYING: 'CLARIFYING',
  IN_REVIEW: 'IN_REVIEW',
  CONFIRMED: 'CONFIRMED',
})

export const IssueStatus = Object.freeze({
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
})

export const ClarificationStatus = Object.freeze({
  WAITING: 'WAITING',
  ANSWERED: 'ANSWERED',
  RESOLVED: 'RESOLVED',
})

export const RevisionStatus = Object.freeze({
  PROPOSED: 'PROPOSED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
})

export const AmbiguityType = Object.freeze({
  QUANTITY_MISSING: 'QUANTITY_MISSING',
  PERFORMANCE_MISSING: 'PERFORMANCE_MISSING',
  CONDITION_MISSING: 'CONDITION_MISSING',
  ACTOR_MISSING: 'ACTOR_MISSING',
  SUCCESS_CRITERIA_MISSING: 'SUCCESS_CRITERIA_MISSING',
  TERM_AMBIGUOUS: 'TERM_AMBIGUOUS',
  EXCEPTION_MISSING: 'EXCEPTION_MISSING',
})

/**
 * Spec §7 비동기 작업 실패 code (`Analysis.error.code`, HTTP는 200).
 * 목록에 없는 코드도 message와 재시도 안내로 처리한다.
 */
export const AnalysisFailureCode = Object.freeze({
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  ANALYSIS_EXECUTION_FAILED: 'ANALYSIS_EXECUTION_FAILED',
  ANALYSIS_INTERRUPTED: 'ANALYSIS_INTERRUPTED',
  CONTENT_VERSION_CONFLICT: 'CONTENT_VERSION_CONFLICT',
})

/** Spec §7 HTTP 오류 code */
export const ApiErrorCode = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ANALYSIS_IN_PROGRESS: 'ANALYSIS_IN_PROGRESS',
  DOCUMENT_ALREADY_ANALYZED: 'DOCUMENT_ALREADY_ANALYZED',
  ANSWER_ALREADY_SUBMITTED: 'ANSWER_ALREADY_SUBMITTED',
  CONTENT_VERSION_CONFLICT: 'CONTENT_VERSION_CONFLICT',
  REQUIREMENT_CONFIRMED: 'REQUIREMENT_CONFIRMED',
  OPEN_ISSUES_EXIST: 'OPEN_ISSUES_EXIST',
  REVISION_ALREADY_PROPOSED: 'REVISION_ALREADY_PROPOSED',
  REVISION_ALREADY_REVIEWED: 'REVISION_ALREADY_REVIEWED',
  ANALYSIS_NOT_RETRYABLE: 'ANALYSIS_NOT_RETRYABLE',
  PREVIEW_VERSION_CONFLICT: 'PREVIEW_VERSION_CONFLICT',
  STATE_CONFLICT: 'STATE_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
})
