spring.application.name=reqbridge

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:app}
spring.datasource.username=${DB_USER:app}
spring.datasource.password=${DB_PASSWORD:app}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
